name: SSH to Ubuntu and Send Logs to Endpoint

on:
  push:
    branches:
      - main

jobs:
  ssh-and-send-logs:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run `pm2 list` command as root and send logs
        run: |
          # Connect to the remote server via SSH and run the command
          LOGS=$(ssh -o StrictHostKeyChecking=no ubuntu@168.231.64.56 "sudo su -c 'source ~/.bashrc && source ~/.nvm/nvm.sh && pm2 list'")

          # Send the logs to a POST endpoint
          curl -X POST https://eom6gmorhd9wp71.m.pipedream.net \
            -H "Content-Type: application/json" \
            -d "{\"logs\": \"${LOGS}\"}"
