name: Call Post Endpoint on Push to Main

on:
  push:
    branches:
      - main

jobs:
  call-post-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make POST request
        run: |
          curl -X POST https://eom6gmorhd9wp71.m.pipedream.net \
            -H "Content-Type: application/json" \
            -d '{"data": "I am about to go vacation"}'
